export default {
  light: {
    colors: {
      header: '#f4f6f6',
      body: '#fff',
      listRow: '#f7f7f7',
      textTitle: '#193b4e',
      textTitleLighter: '#2b4f63',
      textBase: '#41474f',
      textBaseLight: '#909ba6',
      iconBtn: '#636b75',
      divider: '#e1e6eb',
      chip: '#BAA77D',
      disabled: '#c5c7c9',
      tooltip: '#c5c7c9',
      danger: 'red',
    },
  },
  dark: {
    colors: {
      header: 'blue',
      body: 'green',
      listRow: '#f7f7f7',
      textTitle: '#193b4e',
      textTitleLighter: '#2b4f63',
      textBase: '#41474f',
      textBaseLight: '#909ba6',
      divider: '#e1e6eb',
      chip: '#BAA77D',
      disabled: 'grey',
      tooltip: '#c5c7c9',
      danger: 'red',
    },
  },
};
